Remove `brew install python` from Travis OS X conf
The current `brew` installed base in Travis's OS X VMs causes the `brew install python` pre-CI setup command to fail, and reports that Python 2.7.12 is already installed. This commit therefore removes the install command, so that testing can commence with the existing Python install.

-------

Quoting from aaaaalbert/repy_v2@a9fd009ef7200a257614a631b32a096d061942d1 where the problem was first fixed:
"""
This is in response to an error in an [automated continuous integration build](https://travis-ci.org/aaaaalbert/repy_v2/jobs/214290750) that errors out before unit-testing.

After the automatically-run `brew update`, Python 2.7.12 is already installed, and trying to install it once more causes `brew` to fail:

```
brew install python;    ### This is from our .travis.yml CI config and causes the auto update
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/versions).
==> New Formulae
abuse                                    magnetix
advancemame                              mame
advancemenu                              mapcrafter
advancescan                              maven-completion
angband                                  mednafen
angolmois                                mesalib-glw
### ... and many other things
==> Migrating mpfr2 to mpfr@2
==> Unlinking mpfr2
Moving to: /usr/local/Cellar/mpfr@2
==> Linking mpfr@2

Error: python-2.7.12_1 already installed
To install this version, first `brew unlink python`

The command "brew install python;" failed and exited with 1 during .

Your build has been stopped.
```
"""